//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniversity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjVoucherItem
    {
        public AdjVoucherItem()
        {
            this.StockTransactions = new HashSet<StockTransaction>();
        }
    
        public int AdjVoucherItemID { get; set; }
        public Nullable<int> AdjVoucherID { get; set; }
        public string ItemID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
    
        public virtual AdjVoucher AdjVoucher { get; set; }
        public virtual Item Item { get; set; }
        public virtual ICollection<StockTransaction> StockTransactions { get; set; }
    }
}
