//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniversity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Disbursements = new HashSet<Disbursement>();
            this.Employees = new HashSet<Employee>();
            this.StockTransactions = new HashSet<StockTransaction>();
        }
    
        public string DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> CollectionPointID { get; set; }
    
        public virtual CollectionPoint CollectionPoint { get; set; }
        public virtual ICollection<Disbursement> Disbursements { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<StockTransaction> StockTransactions { get; set; }
    }
}
