//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniversity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disbursement
    {
        public Disbursement()
        {
            this.DisbursementItems = new HashSet<DisbursementItem>();
        }
    
        public int DisbursementID { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
        public Nullable<int> CollectionPointID { get; set; }
        public string AcknowledgeEmployeeID { get; set; }
        public string DepartmentID { get; set; }
        public string status { get; set; }
    
        public virtual CollectionPoint CollectionPoint { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<DisbursementItem> DisbursementItems { get; set; }
    }
}
