//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniversity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementItem
    {
        public DisbursementItem()
        {
            this.RequisitionItems = new HashSet<RequisitionItem>();
        }
    
        public int DisbursementItemID { get; set; }
        public Nullable<int> DisbursementID { get; set; }
        public string ItemID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> RemainingQty { get; set; }
        public string Status { get; set; }
    
        public virtual Disbursement Disbursement { get; set; }
        public virtual Item Item { get; set; }
        public virtual ICollection<RequisitionItem> RequisitionItems { get; set; }
    }
}
