//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniversity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Delegates = new HashSet<Delegate>();
            this.Disbursements = new HashSet<Disbursement>();
            this.Requisitions = new HashSet<Requisition>();
        }
    
        public string EmployeeID { get; set; }
        public string PIN { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string DepartmentID { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<Delegate> Delegates { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Disbursement> Disbursements { get; set; }
        public virtual ICollection<Requisition> Requisitions { get; set; }
    }
}
