//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniversity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.AdjVoucherItems = new HashSet<AdjVoucherItem>();
            this.DisbursementItems = new HashSet<DisbursementItem>();
            this.PurchaseOrderItems = new HashSet<PurchaseOrderItem>();
            this.RequisitionItems = new HashSet<RequisitionItem>();
            this.StockTransactions = new HashSet<StockTransaction>();
            this.SupplierItems = new HashSet<SupplierItem>();
        }
    
        public string ItemID { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
        public string UOM { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
        public Nullable<int> ReorderQty { get; set; }
        public string QRCode { get; set; }
        public string BinNo { get; set; }
    
        public virtual ICollection<AdjVoucherItem> AdjVoucherItems { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<DisbursementItem> DisbursementItems { get; set; }
        public virtual ICollection<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual ICollection<RequisitionItem> RequisitionItems { get; set; }
        public virtual ICollection<StockTransaction> StockTransactions { get; set; }
        public virtual ICollection<SupplierItem> SupplierItems { get; set; }
    }
}
