//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniversity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionItem
    {
        public RequisitionItem()
        {
            this.DisbursementItems = new HashSet<DisbursementItem>();
        }
    
        public int RequisitionItemID { get; set; }
        public Nullable<int> RequisitionID { get; set; }
        public string ItemID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Status { get; set; }
        public string Reson { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Requisition Requisition { get; set; }
        public virtual ICollection<DisbursementItem> DisbursementItems { get; set; }
    }
}
