//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniversity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransaction
    {
        public int StockTransactionID { get; set; }
        public string ItemID { get; set; }
        public string SupplierID { get; set; }
        public string DepartmentID { get; set; }
        public Nullable<int> AdjVoucherItemID { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual AdjVoucherItem AdjVoucherItem { get; set; }
        public virtual Department Department { get; set; }
        public virtual Item Item { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
