//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniversity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreEmployee
    {
        public StoreEmployee()
        {
            this.AdjVouchers = new HashSet<AdjVoucher>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
        }
    
        public string StoreEmployeeID { get; set; }
        public string PIN { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<AdjVoucher> AdjVouchers { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    }
}
